-- PHASE IV: CREATING PLUGGABLE DATABASE


-- Creating PDB


  CREATE PLUGGABLE DATABASE Thur_26937_Pacifique_Daily_habit_alarmS_db
  USING 'C:\ORACLE19CC\ORADATA\ORCLL\orcll.xml'
  COPY
  FILE_NAME_CONVERT = (
    'C:\ORACLE19CC\ORADATA\ORCLL\',
    'C:\ORACLE19CC\ORADATA\Thur_26937_Pacifique_Daily_habit_alarmS_db'
  );


-- Opening the PDB

ALTER PLUGGABLE DATABASE Thur_26937_Pacifique_Daily_habit_alarmS_db OPEN;











-- PHASE V: TABLE IMPLEMENTATION AND DATA INSERTION


-- Table Creation


-- USER TABLE
CREATE TABLE users (
    user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(50) UNIQUE NOT NULL,
    email        VARCHAR2(100) UNIQUE NOT NULL,
    password     VARCHAR2(100) NOT NULL,
    created_at   DATE DEFAULT SYSDATE
);

-- HABIT TABLE
CREATE TABLE habit (
    habit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER REFERENCES users(user_id),
    title        VARCHAR2(100) NOT NULL,
    description  VARCHAR2(255),
    frequency    VARCHAR2(20) CHECK (frequency IN ('daily', 'weekly', 'monthly')),
    start_date   DATE,
    status       VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed'))
);

-- GOAL TABLE
CREATE TABLE goal (
    goal_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER REFERENCES users(user_id),
    title        VARCHAR2(100) NOT NULL,
    description  VARCHAR2(255),
    target_date  DATE,
    status       VARCHAR2(20) DEFAULT 'in-progress' CHECK (status IN ('in-progress', 'achieved', 'failed'))
);

-- ALARM TABLE
CREATE TABLE alarm (
    alarm_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id     NUMBER REFERENCES habit(habit_id),
    alarm_time   VARCHAR2(10), -- e.g., '08:00 AM'
    recurrence   VARCHAR2(20),
    is_active    CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N'))
);

-- HABIT_LOG TABLE
CREATE TABLE habit_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id     NUMBER REFERENCES habit(habit_id),
    log_date     DATE,
    status       VARCHAR2(20) CHECK (status IN ('completed', 'missed')),
    note         VARCHAR2(255)
);

-- GOAL_STATUS TABLE
CREATE TABLE goal_status (
    status_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id              NUMBER REFERENCES goal(goal_id),
    update_date          DATE,
    progress_note        VARCHAR2(255),
    completion_percentage NUMBER(5,2) CHECK (completion_percentage BETWEEN 0 AND 100)
);







-- Data insertion


-- USERS TABLE
INSERT INTO users (username, email, password)
VALUES 
('pacifique', 'pacifique@example.com', 'pass123');


INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Morning Workout', 'Cardio and strength', 'daily', SYSDATE - 6, 'active');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Reading', 'Read 30 pages daily', 'daily', SYSDATE - 5, 'active');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Coding Practice', 'LeetCode challenges', 'daily', SYSDATE - 4, 'active');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Journal Writing', 'Write thoughts', 'daily', SYSDATE - 3, 'paused');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Meditation', '10 minutes breathing', 'daily', SYSDATE - 2, 'completed');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Drink Water', '8 glasses daily', 'daily', SYSDATE - 1, 'active');
INSERT INTO habit (user_id, title, description, frequency, start_date, status) VALUES (1, 'Evening Walk', '15 mins after dinner', 'daily', SYSDATE, 'active');


INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Lose 5kg', 'Weight loss goal', SYSDATE + 60, 'in-progress');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Read 10 books', 'By end of term', SYSDATE + 90, 'in-progress');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Get Oracle Certified', 'Finish training + exam', SYSDATE + 45, 'in-progress');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Develop App', 'Build habit tracking app', SYSDATE + 70, 'in-progress');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Improve Sleep', 'Consistent sleep by 10pm', SYSDATE + 30, 'achieved');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Finish SQL Project', 'Capstone phase VIII', SYSDATE + 15, 'in-progress');
INSERT INTO goal (user_id, title, description, target_date, status) VALUES (1, 'Run 5km', 'Without stopping', SYSDATE + 40, 'in-progress');


INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (1, '06:30 AM', 'daily', 'Y');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (2, '08:00 PM', 'daily', 'Y');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (3, '07:00 AM', 'daily', 'Y');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (4, '09:30 PM', 'daily', 'N');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (5, '07:15 AM', 'daily', 'Y');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (6, '09:00 AM', 'daily', 'Y');
INSERT INTO alarm (habit_id, alarm_time, recurrence, is_active) VALUES (7, '06:00 PM', 'daily', 'Y');



INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (1, SYSDATE - 1, 'completed', 'Workout done');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (2, SYSDATE - 2, 'missed', 'Was too tired');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (3, SYSDATE - 1, 'completed', 'Solved 3 problems');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (4, SYSDATE - 3, 'missed', 'Forgot to journal');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (5, SYSDATE - 2, 'completed', 'Felt calm');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (6, SYSDATE - 1, 'completed', 'All 8 glasses done');
INSERT INTO habit_log (habit_id, log_date, status, note) VALUES (7, SYSDATE, 'completed', 'Walked 20 minutes');



INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (1, SYSDATE - 1, 'Lost 1kg', 20);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (2, SYSDATE - 2, '2 books done', 20);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (3, SYSDATE - 1, 'Completed 3 modules', 30);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (4, SYSDATE - 1, 'Wireframe complete', 15);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (5, SYSDATE - 3, 'Sleeping at 10:15pm', 90);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (6, SYSDATE - 1, 'Halfway through PL/SQL', 50);
INSERT INTO goal_status (goal_id, update_date, progress_note, completion_percentage) VALUES (7, SYSDATE, 'Ran 3km nonstop', 60);



SELECT * FROM users;
SELECT * FROM habit;
SELECT * FROM goal;
SELECT * FROM alarm;
SELECT * FROM habit_log;
SELECT * FROM goal_status;













-- PHASE VI: DATABASE INTERACTION AND TRANSACTIONS


-- DML & DDL


-- UPDATE
UPDATE goal
SET status = 'achieved'
WHERE goal_id = 5;

-- DELETE
DELETE FROM habit_log
WHERE status = 'missed';




-- CREATING A PROCEDURE FETCH HABIT LOGS


CREATE OR REPLACE PROCEDURE get_habit_logs (
  p_user_id IN NUMBER
)
IS
BEGIN
  FOR rec IN (
    SELECT h.title, l.log_date, l.status
    FROM habit h
    JOIN habit_log l ON h.habit_id = l.habit_id
    WHERE h.user_id = p_user_id
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('Habit: ' || rec.title || ' | Date: ' || rec.log_date || ' | Status: ' || rec.status);
  END LOOP;
END;



EXEC get_habit_logs(1);






-- FUNCTION CALCULATE GOAL COMPLETION % FROM LOGS

CREATE OR REPLACE FUNCTION get_goal_completion (
  p_goal_id IN NUMBER
) RETURN NUMBER
IS
  v_percent NUMBER;
BEGIN
  SELECT completion_percentage INTO v_percent
  FROM goal_status
  WHERE goal_id = p_goal_id
  ORDER BY update_date DESC
  FETCH FIRST 1 ROWS ONLY;

  RETURN v_percent;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;



SELECT get_goal_completion(1) FROM dual;






-- CURSOR WITH EXCEPTION HANDLING


DECLARE
  CURSOR cur_habits IS
    SELECT title FROM habit WHERE user_id = 1;

  v_title habit.title%TYPE;
BEGIN
  OPEN cur_habits;
  LOOP
    FETCH cur_habits INTO v_title;
    EXIT WHEN cur_habits%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('Habit: ' || v_title);
  END LOOP;
  CLOSE cur_habits;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;






-- PACKAGE EXAMPLE


CREATE OR REPLACE PACKAGE habit_pkg AS
  PROCEDURE log_today_habit(p_habit_id IN NUMBER, p_status IN VARCHAR2);
  FUNCTION active_habit_count(p_user_id IN NUMBER) RETURN NUMBER;
END habit_pkg;
/

CREATE OR REPLACE PACKAGE BODY habit_pkg AS

  PROCEDURE log_today_habit(p_habit_id IN NUMBER, p_status IN VARCHAR2) IS
  BEGIN
    INSERT INTO habit_log (habit_id, log_date, status)
    VALUES (p_habit_id, SYSDATE, p_status);
  END;

  FUNCTION active_habit_count(p_user_id IN NUMBER) RETURN NUMBER IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM habit
    WHERE user_id = p_user_id AND status = 'active';
    RETURN v_count;
  END;

END habit_pkg;





--RUN 
EXEC habit_pkg.log_today_habit(1, 'completed');
SELECT habit_pkg.active_habit_count(1) FROM dual;















-- PHASE VII: ADVANCED DATABASE PROGRAMMING AND AUDITING


-- HOLIDAY TABLE

CREATE TABLE public_holidays (
    holiday_date DATE PRIMARY KEY,
    description  VARCHAR2(100)
);

-- Insert example holidays
INSERT INTO public_holidays VALUES (TO_DATE('01-JUN-2025', 'DD-MON-YYYY'), 'National Heroes Day');
INSERT INTO public_holidays VALUES (TO_DATE('10-JUN-2025', 'DD-MON-YYYY'), 'Independence Day');
INSERT INTO public_holidays VALUES (TO_DATE('30-JUN-2025', 'DD-MON-YYYY'), 'Cultural Celebration');


-- RESTRICTION TRIGGER (Prevent Weekday and Holiday DML)

CREATE OR REPLACE TRIGGER restrict_weekday_and_holiday_dml
BEFORE INSERT OR UPDATE OR DELETE ON habit
FOR EACH ROW
DECLARE
  v_day   VARCHAR2(10);
  v_holiday NUMBER;
BEGIN
  SELECT TRIM(TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=ENGLISH')) INTO v_day FROM dual;

  SELECT COUNT(*) INTO v_holiday
  FROM public_holidays
  WHERE holiday_date = TRUNC(SYSDATE);

  IF v_day IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY') OR v_holiday > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'DML is blocked on weekdays and public holidays!');
  END IF;
END;




-- Auditing table

CREATE TABLE audit_log (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER,
    action_date  DATE DEFAULT SYSDATE,
    operation    VARCHAR2(50),
    status       VARCHAR2(20) -- 'allowed' or 'denied'
);




-- Auditing trigger and status logging

CREATE OR REPLACE TRIGGER audit_habit_dml
AFTER INSERT OR UPDATE OR DELETE ON habit
FOR EACH ROW
DECLARE
  v_user_id NUMBER := 1; -- Simulated, in real app get current session user
BEGIN
  INSERT INTO audit_log (user_id, operation, status)
  VALUES (v_user_id, 'MODIFY HABIT', 'allowed');
END;


-- operations to test trigger trigger

INSERT INTO habit (user_id, title, description, frequency, start_date)
VALUES (2, 'Wake up early', 'Wake up by 5AM daily', 'daily', SYSDATE);

UPDATE habit SET status = 'paused' WHERE habit_id = 1;

DELETE FROM habit WHERE habit_id = 1;


--test
SELECT * FROM audit_log ORDER BY audit_id;



